### ISSUE TITLE
usage summaries are rejected

### ISSUE THREAD

**Issue by 404pilot** [rackerlabs/standard-usage-schemas#476]
Hi all, there are two type of events rejected by summary event feeds.

* backup summary events are rejected if no `serverID` is specified, but `serverID` is not needed for usage summary
* sites summary events are rejected if the value of `computeCycles` exceeds the max value defined in product schema, but product schema should only restrict usage events not usage summary events based on those attribute

I am wondering if there is a way to remove those validations for usage summary events.

Any thoughts?

@RackerHector 

#### cloud backup

**endpoint**: `/usagesummary/backup/events`

**event**:

```xml
<atom:entry xmlns:atom="http://www.w3.org/2005/Atom">
    <atom:content type="application/xml">
        <event dataCenter="ORD1"
               duration="PT24H"
               endTime="2015-05-20T00:00:00.000Z"
               id="f6b737cf-97d7-4552-96e1-f683eef329f4"
               rackspaceAccountNumber="021-20004222"
               region="ORD"
               resourceId="RESOURCE_ID_2"
               resourceName="Entry Testing QE"
               startTime="2015-05-19T00:00:00.000Z"
               tenantId="20004222"
               type="USAGE_SUMMARY"
               version="1"
               xmlns="http://docs.rackspace.com/core/event">
            <prod:product resourceType="AGENT"
                          serviceCode="CloudBackup"
                          version="3"
                          xmlns:prod="http://docs.rackspace.com/usage/cloudbackup/license"/>
        </event>
    </atom:content>
</atom:entry>
```

**reject reason**:

``` xml
<error
        xmlns="http://abdera.apache.org"
        xmlns:db="http://docbook.org/ns/docbook"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:event="http://docs.rackspace.com/core/event"
        xmlns:dbaas="http://docs.rackspace.com/usage/dbaas"
        xmlns:maas="http://docs.rackspace.com/usage/maas"
        xmlns:lbaas="http://docs.rackspace.com/usage/lbaas"
        xmlns:lbaas-account="http://docs.rackspace.com/usage/lbaas/account"
        xmlns:cbs="http://docs.rackspace.com/usage/cbs"
        xmlns:cbs-snap="http://docs.rackspace.com/usage/cbs/snapshot"
        xmlns:cf-b="http://docs.rackspace.com/usage/cloudfiles/bandwidth"
        xmlns:cf-cdn="http://docs.rackspace.com/usage/cloudfiles/cdnbandwidth"
        xmlns:cf-str="http://docs.rackspace.com/usage/cloudfiles/storage"
        xmlns:rax="http://docs.rackspace.com/api"
        xmlns:atom="http://www.w3.org/2005/Atom">
    <code>400</code>
    <message>Bad Content: Element prod:product does not satisfy assertion. If the server is NOT external, then the
        serverID attribute is required.
    </message>
</error>
```

#### cloud sites

**endpoint**: `/usagesummary/sites/events`

**event**:

``` xml
<atom:entry xmlns:atom="http://www.w3.org/2005/Atom">
    <atom:content type="application/xml">
        <event dataCenter="ORD1"
               duration="PT5H"
               endTime="2015-05-19T21:00:00.000Z"
               id="d9bbe694-48d8-40db-a309-9a6eb672d407"
               parentTenantId="20001806"
               rackspaceAccountNumber="021-20004180"
               region="ORD"
               resourceId="RESOURCE_ID_2"
               resourceName="Entry Testing QE"
               startTime="2015-05-19T09:00:00.000Z"
               tenantId="20004180"
               type="USAGE_SUMMARY"
               version="1"
               xmlns="http://docs.rackspace.com/core/event">
            <prod:product bandWidthOut="2833664392461"
                          computeCycles="14845.30347452"
                          resourceType="SITE"
                          serviceCode="CloudSites"
                          version="1"
                          xmlns:prod="http://docs.rackspace.com/usage/sites/metered"/>
        </event>
    </atom:content>
</atom:entry>
```

**reject reason**:

``` xml
<error
        xmlns="http://abdera.apache.org"
        xmlns:db="http://docbook.org/ns/docbook"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:event="http://docs.rackspace.com/core/event"
        xmlns:dbaas="http://docs.rackspace.com/usage/dbaas"
        xmlns:maas="http://docs.rackspace.com/usage/maas"
        xmlns:lbaas="http://docs.rackspace.com/usage/lbaas"
        xmlns:lbaas-account="http://docs.rackspace.com/usage/lbaas/account"
        xmlns:cbs="http://docs.rackspace.com/usage/cbs"
        xmlns:cbs-snap="http://docs.rackspace.com/usage/cbs/snapshot"
        xmlns:cf-b="http://docs.rackspace.com/usage/cloudfiles/bandwidth"
        xmlns:cf-cdn="http://docs.rackspace.com/usage/cloudfiles/cdnbandwidth"
        xmlns:cf-str="http://docs.rackspace.com/usage/cloudfiles/storage"
        xmlns:rax="http://docs.rackspace.com/api"
        xmlns:atom="http://www.w3.org/2005/Atom">
    <code>400</code>
    <message>Bad Content: Validating product/@computeCycles: Value "14845.30347452" contravenes the maxInclusive facet "12500" of the type computeCycles1Type</message>
</error>
```

**Comment by usnavi** [comment]
Hi Hector,

All usagesummary schemas are automatically generated from the corresponding product schema definitions.  For the cloudbackup/license events,  the following are set:

            <attribute name="external" type="boolean" use="optional" default="false">
                If this value is set to true, the server where the agent is installed is external to Rackspace.
            </attribute>
            <xpathAssertion test="if (not(xsd:boolean(@external))) then @serverID else true()">
                If the server is NOT external, then the serverID attribute is required.
            </xpathAssertion>

If the assert isn$B!G(Bt valid for for the summary events, we$B!G(Bll need to update it so it doesn$B!G(Bt get triggered for summary events.  We can do the same for sites as well.

When would you need this in prod?  Whats the relative priority?

Thanks,

Greg

**Comment by 404pilot** [comment]
I find some events are able to be posted even with values exceeding max value or unmatching the type of field defined in product schema. I guess usage summary validation is able to be deactivated without changing product schema. Is that true?

* the max of `bandwidthOut` is 109951162777600
```xml
<atom:entry
    xmlns:atom="http://www.w3.org/2005/Atom"
    xmlns="http://docs.rackspace.com/core/event"
    xmlns:cf-b="http://docs.rackspace.com/usage/cloudfiles/bandwidth">
    <atom:id>urn:uuid:f6b737cf-97d7-4552-96e1-f683eef329f5</atom:id>
    <atom:category term="tid:1234" />
    <atom:category term="rgn:DFW" />
    <atom:category term="dc:DFW1" />
    <atom:category term="cloudfiles.bandwidth.usage_summary" />
    <atom:category term="type:cloudfiles.bandwidth.usage_summary" />
    <atom:content type="application/xml">
        <event dataCenter="DFW1" duration="PT16H" endTime="2012-06-14T22:19:52.000Z" environment="PROD" id="f6b737cf-97d7-4552-96e1-f683eef329f5" rackspaceAccountNumber="020-1234" region="DFW" startTime="2012-06-14T06:19:52.000Z" tenantId="1234" type="USAGE_SUMMARY" version="1">
            <cf-b:product bandwidthIn="4" bandwidthOut="109951162777700" serviceCode="CloudFiles" summary="true" version="1" />
        </event>
    </atom:content>
    <atom:link href="https://atom.staging.ord1.us.ci.rackspace.net/usagesummary/files/events/entries/urn:uuid:f6b737cf-97d7-4552-96e1-f683eef329f5" rel="self" />
    <atom:updated>2015-06-03T15:32:31.038Z</atom:updated>
    <atom:published>2015-06-03T15:32:31.038Z</atom:published>
</atom:entry>
```

* the type of `storage` is Long
``` xml
<atom:entry
    xmlns:atom="http://www.w3.org/2005/Atom">
    <atom:id>urn:uuid:f6b737cf-97d7-4552-96e1-f683eef329f6</atom:id>
    <atom:category term="tid:5823641" />
    <atom:category term="rgn:DFW" />
    <atom:category term="dc:DFW1" />
    <atom:category term="rid:SC51-1-US" />
    <atom:category term="cloudsites.db.mssql.usage_summary" />
    <atom:category term="type:cloudsites.db.mssql.usage_summary" />
    <atom:content type="application/xml">
        <event
            xmlns="http://docs.rackspace.com/core/event"
            xmlns:db="http://docs.rackspace.com/usage/sites/db" dataCenter="DFW1" duration="PT24H" endTime="2012-08-06T00:00:00.000Z" environment="PROD" id="f6b737cf-97d7-4552-96e1-f683eef329f6" rackspaceAccountNumber="020-5823641" region="DFW" resourceId="SC51-1-US" resourceName="mssqldb" startTime="2012-08-05T00:00:00.000Z" tenantId="5823641" type="USAGE_SUMMARY" version="1">
            <db:product resourceType="MSSQL" serviceCode="CloudSites" storage="3950.1" summary="true" version="1" />
        </event>
    </atom:content>
    <atom:link href="https://atom.staging.ord1.us.ci.rackspace.net/usagesummary/sites/events/entries/urn:uuid:f6b737cf-97d7-4552-96e1-f683eef329f6" rel="self" />
    <atom:updated>2015-06-03T15:39:36.422Z</atom:updated>
    <atom:published>2015-06-03T15:39:36.422Z</atom:published>
</atom:entry>
```

**Comment by usnavi** [comment]
Hi,

The schemas generated for the usage summary feeds are slightly different than those for the normal feed.  A brief summary can be found here:  https://github.com/rackerlabs/standard-usage-schemas/pull/232

In particular,


  1.  If an attribute has an aggregation function of SUM then, if the type of the attribute is of type int, long, short, or byte then the attribute for the USAGE_SUMMARY will be of type integer. If the type of the attribute is of type unsignedInt, unsignedLong, unsignedShort, or unsignedByte then the attribute for the USAGE_SUMMARY message will be nonNegativeInteger. Any range facets will also be removed.

So for bandwidthOut, the max is removed.   Where did you get the line about it having a max?  If it was from our docs, we$B!G(Bll definitely need to fix it, but I didn$B!G(Bt see it.

The aggregateFunction is set in the product schema here:  https://github.com/rackerlabs/standard-usage-schemas/blob/master/sample_product_schemas/cloudfilesBandwidthUsage.xml

For storage, since its an average value, it$B!G(Bs a double.  The product schema is here:  https://github.com/rackerlabs/standard-usage-schemas/blob/master/sample_product_schemas/sites-db.xml

Greg

**Comment by 404pilot** [comment]
Oh I found that max value in usage product schema. I think I shouldn't mix usage schema and usage summary schema together.

Anyway, could you please remove those two validations just for `usage summary` event I mentioned in the first message?

**Comment by usnavi** [comment]
We can do that.  Can we move this to cloudfeeds@RACKSPACE.COM?

Thanks,

Greg

**Comment by 404pilot** [comment]
Yes please. 

Thanks! And please inform me of this change made in staging endpoints so usage qe can start to test it.

**Comment by usnavi** [comment]
404Pilot - who are you in real life?  We need a contact name :-)

**Comment by usnavi** [comment]
Some more notes:

The constraint for the cloudbackuplicenses is doable and I've created a story for that.

As for the sites constraint, that is a bug in how we generate usagesummary events and we'll have to dig into that.  Can we put that on the backburning until we get our EA release out?  Most likely we can get to this at the end of July.  Does that work?

thanks

**Comment by shintasmith** [comment]
@404pilot, can we close this?

**Comment by 404pilot** [comment]
@shintasmith Yes, please. Thanks!
