### ISSUE TITLE
Update error responses

### ISSUE THREAD

**Issue by shintasmith** [rackerlabs/standard-usage-schemas#535]
Right now we dont have any descriptions on the different type of error responses. We should document the following:
https://one.rackspace.com/display/cloudfeeds/Rules+for+Publishers+and+Subscribers#RulesforPublishersandSubscribers-ResponseCodes.

**Comment by shintasmith** [comment]
@meker12 and @stanzikratel, FYI

**Comment by shintasmith** [comment]
This one for the POST methods, for publishers: https://one.rackspace.com/display/cloudfeeds/Rules+for+Publishers+and+Subscribers#RulesforPublishersandSubscribers-ResponseCodes

**Comment by meker12** [comment]
Hi Shinta,

I submitted PR #536  to add the updated common.ent file; the productSchema.xsl, and the feed.wadl to include the reponse tables.

When I built locally, the Get Feed errors codes do come out in the table format.  

However, in the product.wadl, some of the response codes come out in the table format, but then some do not.

For example, in the product.wadl, the error codes in this method:  ```"getEntryCustomerServiceTenant```

have the response codes with the title and message-- I believe the codes in this method are coming from the productSchema.xsl. 

But, in the ```addCustomerServiceEntry``` method, the error codes are hard coded.

**Comment by meker12** [comment]
@shintasmith  In PR #536 -  I added the changes that will fill out the response code tables with the errors and descriptions.  

When I looked at the feeds.wadl, it looked like the response code text in there is part of that WADL, and not generated.  Can you confirm that?

If the response code text in the feeds.wadl is generated, then we would have to change the source. 

Also, I'm going to try to run a Jenkins build on my fork to see if the output of the docbook comes out the same.

**Comment by shintasmith** [comment]
feeds.wadl is not generated. The only wadl that's generated is product.wadl.

**Comment by meker12** [comment]
OK.  So I think that you can review and merge these changes. If they look OK.

**Comment by meker12** [comment]
So I built the Cloud Feeds content off of my fork.   The error tables are coming through in the DocBook.  Forgot the 200 title and response.  Will update.

@shintasmith  See the fix here:  http://docs-staging.rackspace.com/jenkins/job/Cloud-Feeds-Test-Build/ws/target/docbkx/webhelp/feeds-devguide-external/content/GET_getEntryCloudBackupTenant_backup_events__tid__entries__id__backup.product.html

**Comment by meker12** [comment]
We can close this issue when we merge #536 .  It has some other stuff in it as well.  Will update the PR description when ready.

**Comment by shintasmith** [comment]
Nice, @meker12, :+1: 

I noticed a few things:
* The title seems to get lost. In here: http://docs-internal.rackspace.com/cloud-feeds/api/v1.0/feeds-devguide/content/GET_getEntryCloudBackup_backup_events_entries__id__backup.product.html, the title is actually "Get Cloud Backup Event"
* Error code 401 and 409 actually don't make sense for GET method, but our existing doc listed them out. So I guess we can keep them here and think about hiding them later. Let's get the migration done first, then we can fine tune! :-)
* The attributes of the events (in the event's payload) don't show up anymore. 
* The samples XML and JSON are also not included. 

I think my PR to fix _0:doc actually undid the last 2. :-( Let me do a doc build locally and fix those

**Comment by meker12** [comment]
@stanzikratel and @shintasmith Going to move the previous comments to new issues, and close this one.
