### ISSUE TITLE
WADL2RST conversion - remove 409 error responses from GET events

### ISSUE THREAD

**Issue by meker12** [rackerlabs/standard-usage-schemas#543]
- [ ] Remove error 409 from the response table for "GET operations."
- [ ] Remove error code 401 from response table for "GET operations"  (Can't you get unauthorized when you do a GET request?)

**Comment by shintasmith** [comment]
401 is a valid response code for GET requests

**Comment by meker12** [comment]
Thanks for fixing this.  I'm not sure if you noticed, but in the Cloud Feeds WADL, I added the common.ent file. 

It has commonFaults, getFaults, and postFaults. 

So it's possible to replace the error response section of the WADL to look like this:
```
<!-- On Error -->
         &commonFaults;
         &getFaults;
```

**Comment by shintasmith** [comment]
@meker12, the &commonFaults; is not appropriate for GET requests. It listed out 429 and 409. The &getFaults; also included 409. 

I am thinking there's not much benefit to having this common.ent file. When the WADL is hand-edited, it makes sense to have common.ent file so that we don't have to re-type the responses for every single resource. 

But our WADL is generated anyways. When we make changes to the responses, we make them in productSchema-wadl.xsl, just one place, it gets replicated to all resources when we run the XSLT.

**Comment by meker12** [comment]
so the common.ent file that I put in this repo doesn't include 409 for the Get faults.  I removed that. This is the one that I referenced from the feeds.wadl. 

https://github.com/rackerlabs/standard-usage-schemas/blob/master/src/docbkx/common/common.ent

So you cannot get a Rate limit error on a GET request?  

In our hand-edited WADL, we included the common.ent because it saved you from repeating the same information over and over and makes the WADL cleaner and easier to read. 

However, if you want to remove it from the feeds.wadl, and replace the error codes with the block messages, let me know.

**Comment by shintasmith** [comment]
@meker12, gotcha on the 409 for GET faults. I don't know what I was looking at...

You can get a Rate limit on a GET request, but currently the description says "Retry until the entry is posted." 

Ok. Let me see if I can use the common.ent in product.wadl. It'll probably be Monday, tho.

**Comment by shintasmith** [comment]
@meker12, I have some issues with generating this snippet into the product.wadl:
```
<!DOCTYPE application[
<!ENTITY % common SYSTEM "../src/docbkx/common/common.ent">
    %common;
]>
```
First of all, that is an embedded DOCTYPE. There is a support for XSLT to output a DOCTYPE public that will generate something like this:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
```
by using this in our XSLT:
```
<xsl:output media-type="text/html" method="html" encoding="windows-1251" doctype-public="-//W3C//DTD XHTML 1.1//EN" doctype-system="http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd" omit-xml-declaration="yes"/>
```
But our DOCTYPE declaration has embedded DTD. I haven't found a way to do it with ```xsl:output```. 

See this article: http://www.xml.com/lpt/a/1027, that basically says: The DOCTYPE declarations added this way can only point to external DTD files.

I tried using this:
```
 <xsl:text disable-output-escaping='yes'>&lt;!DOCTYPE application[
&lt;!ENTITY  % common SYSTEM "../src/docbkx/common/common.ent"&gt;
    %common;
]&gt;
 </xsl:text>
```
But Saxon prohibits me from doing that. It threw an error: 
```
SEVERE: err:XD0001:Only whitespace text nodes can appear at the top level in a document
```

cc: @usnavi

**Comment by shintasmith** [comment]
@meker12, I am tempted to just keep what we have. It's not perfect. But it's not that bad. I mean how many times will the response code description changes?

**Comment by meker12** [comment]
@shintasmith   I agree. Not worth the effort.  

 I did update the response code description for the 429 error, so you might want update any occurrences of that one that show up in the output.  

The PR that has the new text is in the PR queue now. 

Did the CADF.wadl change that Constanze made come out OK?

**Comment by shintasmith** [comment]
@meker12, yes, the Constanze's cadf.wadl changes have been merged in. Waiting on the build for your PR. Once that finishes successfully, I will merge in.
