### ISSUE TITLE
Update cadf.wadl to add response codes and descriptions

### ISSUE THREAD

**Issue by meker12** [rackerlabs/standard-usage-schemas#547]
User access events in CADF wadl are missing the response name and description. 

You can fix this using the same approach used in the [feeds.wadl](https://github.com/rackerlabs/standard-usage-schemas/blob/master/wadl/feed.wadl).

Add a link reference to the common.ent file in the Application section at the top of file.
Replace the error response enumeration (400 and 500) with the variables. 

For GET operations, use  
``
         &commonFaults;
         &getFaults;
```

For POST operations, use 

```
         &commonFaults;
         &postFaults;
```

For response codes (200 and 201),  replace the existing code with these:

```
       <response status="200">
            <wadl:doc xmlns="http://docbook.org/ns/docbook" title="OK" xml:lang="EN">The request succeeded.</wadl:doc>
            <representation mediaType="application/json"/>
         </response>
```
```
 <response status="201" >
            <wadl:doc  xmlns="http://docbook.org/ns/docbook" title="Created"  xml:lang="EN">The request has been fulfilled. The entry has been created.</wadl:doc>
        </response>
```

**Comment by meker12** [comment]
If you don't want to use the common.ent file, you can just replace the existing error messages with the code that includes the response title and message.

**Comment by stanzikratel** [comment]
Updated cadf.wadl with references to common.ent and submitted a pull request

**Comment by shintasmith** [comment]
This is addressed in PR #550. Can we close this issue, @meker12 ?

**Comment by meker12** [comment]
Only one set of codes was changed.  Just submitted a PR to change the second set.  After that is merged, we can close this issue.

**Comment by shintasmith** [comment]
@meker12, PR #556 has been merged.

**Comment by shintasmith** [comment]
@stanzikratel can you follow up with @meker12 and see if this issue can be closed? Thanks!

**Comment by stanzikratel** [comment]
@shintasmith will do. I'm in training in SAT today and Margaret is at a conference but I will try to track her down soon!
